import "./globals.css";

import ProviderContainer from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {/* provider container for wrapping complete compoents inside redux store and making root layout as a server component for
          making app SEO friendly */}
          <ProviderContainer> 
            {children}
          </ProviderContainer>
      </body>
    </html>
  );
}
